[[resources]]
name = "dashboard"
route = "/"
source = "http://localhost:3000"
restricted = false

[[resources]]
name = "auth"
route = "/auth"
source = "http://localhost:3001"
restricted = false

[[resources]]
name = "api"
route = "/api"
source = "http://localhost:3001"
restricted = false
